//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_OrderProduct
    {
        public int Inv_OrderProductId { get; set; }
        public Nullable<int> Inv_OrdersId { get; set; }
        public Nullable<int> Inv_ProductId { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Inv_Orders Inv_Orders { get; set; }
        public virtual Inv_Product Inv_Product { get; set; }
    }
}
