//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Product
    {
        public Inv_Product()
        {
            this.Inv_OrderProduct = new HashSet<Inv_OrderProduct>();
        }
    
        public int Inv_ProductId { get; set; }
        public int Inv_ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductDetails { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<Inv_OrderProduct> Inv_OrderProduct { get; set; }
        public virtual Inv_ProductType Inv_ProductType { get; set; }
    }
}
