//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Orders
    {
        public Inv_Orders()
        {
            this.Inv_OrderProduct = new HashSet<Inv_OrderProduct>();
            this.Inv_ProductInventory = new HashSet<Inv_ProductInventory>();
        }
    
        public int Inv_OrdersId { get; set; }
        public Nullable<int> Inv_CustomerId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderDetails { get; set; }
        public Nullable<int> TotalUnit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string UnitofMeasurementCode { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Inv_Customer Inv_Customer { get; set; }
        public virtual ICollection<Inv_OrderProduct> Inv_OrderProduct { get; set; }
        public virtual ICollection<Inv_ProductInventory> Inv_ProductInventory { get; set; }
    }
}
